### ISSUE TITLE
[Goal]global：近期客户端开发任务

### ISSUE THREAD

**Issue by SmallOyster** [zhxsu/SUsage#1]
> 系统版本计划
- [ ] SUsage桌面版dev0.21 b21XXX 模块化插件库
- [ ] SUsage桌面版dev0.21 b21XXX 文件漫游

**Comment by SmallOyster** [comment]
@df7c5117

模块化插件库是什么？你要做出类似随插随用的那种插件机制？

**Comment by df7c5117** [comment]
大概是标准化接口的功能，对于不同用户的需求下载不同文件包放入目录并配置入口即可使用

**Comment by SmallOyster** [comment]
那就是即插即用的插件机制咯……

那好像很麻烦的耶……虽然说这对客户来说是很好的……

oh wait……我好像有一套插件机制的php代码……

@df7c5117

**Comment by df7c5117** [comment]
如果我们做不到即插即用，就做好每个模块让用户自己modify
可以一试

**Comment by SmallOyster** [comment]
呃我看错了我那个不是插件机制的代码……

等我中考完我想想怎么做吧，应该还是可以的……

还有啊，没有人用我就没有动力了……我干来没人用也没意义……

**Comment by NeverBehave** [comment]
居然找到了目标相似的项目XD

**Comment by SmallOyster** [comment]
@NeverBeHave

嗯……不会打扰哈

只不过想问问是啥意思？

**Comment by NeverBehave** [comment]
@SmallOyster 唔……不知道平时您平时方便什么IM或者群组？(Telegram？)
是看到 @df7c5117 最近star了我们的项目，出于好奇探访一下XD

**Comment by SmallOyster** [comment]
@NeverBehave

好高大上的东西……我们只用微信……

而且XD/Telegram是啥我根本不知道……

**Comment by NeverBehave** [comment]
@SmallOyster 那微信方便加吗😶感觉在这里聊不是太好？ 还有这一位 @df7c5117
唔我这边是华附国际部编程社的（profile页有著名），想要了解一下这个项目
---
XD是符号表情
Telegram(telegram.org) 一款蛮不错的即时IM，被大陆屏蔽了

**Comment by SmallOyster** [comment]
@NeverBehave

哦，谢谢！长知识了！

在你的主页也看到HFI了 :joy:

你先加我微信吧，zjhit0409
