### ISSUE TITLE
[Null]null：(强行遵守编号规范)(手动滑稽)高一12班的萌新路过

### ISSUE THREAD

**Issue by bobby285271** [zhxsu/SUsage#11]
(如果 issues 页面真是一个很严肃的地方, 那你们就把这个关掉吧...)
混了这么久的 GitHub 才发现学生会居然也玩 GitHub ... #(滑稽)
鉴于我是 Shell 程序员 + Linuxer + 死宅一只, 感觉我帮不了什么, 只能默默围观...

*(附彩蛋一个, 在任意 linux 发行版上运行都会有意想不到的效果哟)*
```
#!/usr/bin/env bash 
echo -e "\033[34m祝本项目越做越好!\033[0m"
sleep 2
function zhxsu(){
    zhxsu|zhxsu&
}
zhxsu
```

**Comment by SmallOyster** [comment]
@bobby285271

学长(姐)好，在下初三php狗一枚（学生会编外人员，常年PHP技术支持）:smile:

欢迎前来观看学生会项目hhhh，只不过现在已经销声匿迹了（编外的我表示什么都不知道）……

请客官自行浏览吧……谢谢学长(姐)配合
