### ISSUE TITLE
[Advice]All：建议所有CSS/JS文件使用Bootcdn

### ISSUE THREAD

**Issue by SmallOyster** [zhxsu/SUsage#12]
建议所有页面的CSS/JS文件都采用Bootcdn的，因为这样可以省去对服务器的访问，而且还可以提升客户访问的速度，并且防止某些恶意刷流量。

而且建议使用min文件，文件更小、访问更快哦！

**Comment by df7c5117** [comment]
理解
1.这一版将大量bootstrap的默认样式自定义化了
2.没有压缩是因为样式还没定型

**Comment by SmallOyster** [comment]
哦~原来是这样……好吧我懂了。谢谢您的回复！

如果有任何关于后端的事情，随时欢迎呼叫我哦~

**Comment by SmallOyster** [comment]
@df7c5117

欢迎关注我的新项目哈~

**Comment by df7c5117** [comment]
那个 有限公司不是随便叫的。。。

**Comment by SmallOyster** [comment]
管他呢反正GitHub不会去查😂写着先呗
