### ISSUE TITLE
[Goal]Admin：人生大事 の 后台开发进度

### ISSUE THREAD

**Issue by JerryLoveZhiXin** [zhxsu/SUsage#2]
本贴仅提供以下功能

发布后台开发进度

欢迎各位在本贴对我的工作做评价

我尽量做到实时更新

感谢各位！ :smile:

**Comment by JerryLoveZhiXin** [comment]
## 20160518 -- 20160519

 1. 导航栏(权限菜单)
 2. 所有用户显示
 3. 用户信息管理
 4. 重置用户密码

---

### 预览未来

 1. 发布全局通知
 2. 管理员设置/权限分配
 3. 所有任务管理

**Comment by JerryLoveZhiXin** [comment]
## 20160520 -- 20160522

 1. 任务列表
 2. 用户角色编辑（**组长、管理员、超管**）

---

### 预览未来

 1. 发布全局通知
 2. 角色权利列表

---

### P.S.

 还有其他功能吗？貌似没有了耶

**Comment by JerryLoveZhiXin** [comment]
## 20160522 -- 20160525

### 已完成

- [ ]  1. 任务删除

---

### 预览未来

- [ ]  2. 查看角色权限

---

### P.S.

@df7c5117 
 还有其他功能吗？貌似没有了耶

**Comment by JerryLoveZhiXin** [comment]
## 20160526

### 已完成

- [x]  1. 查看角色权限

---

### 预览未来

- [ ]  1. 登录/SESSION

---

### P.S.

@df7c5117  
还有其他功能吗？貌似没有了吧

**Comment by JerryLoveZhiXin** [comment]
# 20160526

## **系统基本完工**

## 嘟嘟嘟~手机短信

@df7c5117 

### **请签收来自生蚝速递的包裹！**

**Comment by df7c5117** [comment]
吼啊！！！！！！！
