### ISSUE TITLE
[Note]global：issue编号规范version2.4

### ISSUE THREAD

**Issue by df7c5117** [zhxsu/SUsage#3]
接下来本项目提出的issues，将使用统一编号规范，便于管理及归档。
## 具体规范如下：

**[项目类型]+解决状态（可选）+下划线+对象编码+：+主题**

**\- 项目类型**

请参照归档标签填写，如labels=bug就填写bug

**\- 解决状态（可选）**

已解决：fixed；未解决：unfixed

**\- 对象编码**

对于各板块的对象。

全局：global
发布系统：post
文件系统：file
登陆界面：login
个人中心：ucent
任务及展望：tasks
系统后台：Admin
账务公开 : bill

**Comment by JerryLoveZhiXin** [comment]
**基于强迫症（标题对齐）**
**已把本文Label改成note**
**以对齐其他issues**
**请原谅~~**

**Comment by df7c5117** [comment]
吼啊
