### ISSUE TITLE
[Bug]unfixed_global：系统bug汇总

### ISSUE THREAD

**Issue by df7c5117** [zhxsu/SUsage#4]
> 主页

- [x] 发布框是否为空判定 **_1D84 160718_**

- [x] F5键锁定和某些js冲突 **_1D86 160720_**

---

> 任务

- [x] [160729] 更新后无法发送任务 **_1E98 160730_**

- [ ] [160730] 任务列表的排序

---

> 后台

- [x] [160529] 普权用户登录漏洞 **_1D33 160710_**

- [x] [160718] “发布任务”中选择部门的复选框无法选中  **_1E32 160725_**

- [x] [160730] 管理员可以重置用户密码的漏洞 **_2A12 160801_**

- [x] [160730] 编辑用户资料的SQL语句 **_2A12 160801_**

---

> 前台登录

- [x] [160725] “记住用户名”选中后不能实现对应功能 **_1E44 160726_**

- [x] [160729] 未登录的用户也可以闯入平台 **_1E88 160729_**

**Comment by JerryLoveZhiXin** [comment]
回车发信息也有Bug吗（我测试时是可以的喔~）

**Comment by df7c5117** [comment]
按了enter并没有反应

**Comment by JerryLoveZhiXin** [comment]
哦。我去看看。

**Comment by SmallOyster** [comment]
- 任务发布模块

- [ ] 选择部门的复选框无法选中

**Comment by df7c5117** [comment]
目前所有bug已经解决

**Comment by SmallOyster** [comment]
有bug请先reopen在填写记录。感谢配合！

**Comment by SmallOyster** [comment]
- 登录

- [ ] 选中后不能记住用户名

**Comment by df7c5117** [comment]
这样吧 以后的记录统一在第一个comment那里添加 便于系统记录进度

**Comment by SmallOyster** [comment]
@df7c5117

好哒~收到啦~

我过会儿会把现在这条删掉的，上面的留着。

只有所有bug解决了才关闭，有新bug就先reopen再编辑。

**Comment by df7c5117** [comment]
嗯
