### ISSUE TITLE
[Goal]chat：今夜，我做了一个艰难的决定

### ISSUE THREAD

**Issue by df7c5117** [zhxsu/SUsage#5]
经过我和电脑部领导人的微信群的一致意见，我们正式决定移除系统的聊天功能。

原因如下：
1.使用率低，并且不如其他平台方便。私聊布置任务，可能更多人选择wechat等。这个功能上线后，用户流量和KPI等不如预期，很可能成为鸡肋
2.技术上有瓶颈，当前bug存在普遍，耗费资源精力，拖延上线时间。

综上所述，我将在接下来1~2个commit中移除chat有关文件。
辛苦你们了，抱歉 @SmallOyster @yyl99311

**Comment by SmallOyster** [comment]
就当一次练兵吧……不要紧了删掉吧……这东西确实挺耗流量的。

**Comment by SmallOyster** [comment]
而且也真做不到实时聊天，也有挺多bug

**Comment by SmallOyster** [comment]
只不过我还是申请加入你们的微信群。
