### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by yyl99311** [zhxsu/SUsage#9]
issue

**Comment by zhangjingye03** [comment]
Hello lazy group manager

Long time no see on Github

How about your brilliant serial console?

**Comment by SmallOyster** [comment]
@yyl99311

Hello!

Do you have a Project built by Java? I want to see it!

But I Hear of Study Java is More Difficult, is it?

**Comment by zhangjingye03** [comment]
@SmallOyster Here it is: https://github.com/yyl99311/SerialReader

Java unfortunately isn't as simple as C# or PHP unless   you can remember and recognize mountains of class names, and you have to bear the troublesome & unconvenient compiling and debugging environment as well as terrible runtime speed.

**Comment by zhangjingye03** [comment]
@SmallOyster Your English seems terrible :joy:

**Comment by SmallOyster** [comment]
@zhangjingye03

em...... My English Teacher was old and bad :joy:

I heard Java is very difficult to learn.

Fortunately, I chose the right language :smile:

**Comment by SmallOyster** [comment]
java have more package and function! ohhhhhhh!

YYL, how to remember that all code?

**Comment by yyl99311** [comment]
Java is beautiful.

**Comment by yyl99311** [comment]
Just remember those necessary codes and look up the tool book when you forget some uncommon codes.

**Comment by zhangjingye03** [comment]
@yyl99311 
![](https://cdn.meme.am/instances/27878619.jpg)
--Linus

**Comment by SmallOyster** [comment]
@yyl99311 

Java's Code is too longggggggg.........

---

@zhangjingye03 

Don't Attack other languages.......
